{
    "name": "Alfresco Report Integration",
    "version": "1.0",
    "summary": "Upload PDF reports to Alfresco automatically",
    "category": "Tools",
    'author': 'Javier, F3nrir',
    'company': 'ASI S.U.R.L.',
    'website': 'https://antasi.asisurl.cu',
    "depends": ["base", "web", "asi_pdf_signature"],
    'external_dependencies': {
        'python': ['requests','pypdf'],
    },
    "data": [
        "security/alfresco_groups.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/alfresco_report_mapping_views.xml",
        "views/alfresco_views.xml",       
        "data/cron_sync_alfresco.xml",
        "data/cron_export_reports.xml",
    ],
   'images': ['static/description/icon.png'],
    "installable": True,
    "auto_install": False,
    "application": False,
}
