{
    "name": "Alfresco Report Integration",
    "version": "1.0",
    "summary": "Upload PDF reports to Alfresco automatically",
    "category": "Tools",
    'author': 'Javier',
    'website': 'https://www.asisurl.cu',
    "depends": ["base", "web"],
    "data": [
        "views/res_config_settings_views.xml",
        "views/alfresco_report_mapping_views.xml",
        "views/alfresco_views.xml",
        "security/ir.model.access.csv",
        'data/cron_sync_alfresco.xml',
    ],
   'images': ['static/description/icon.png'],
    "installable": True,
    "auto_install": False,
    "application": False,
}
